### ISSUE TITLE
error 'BlenderVR_root' is not defined

### ISSUE THREAD

**Issue by jmespadero** [BlenderVR/blender-vr#32]
I can't launch blenderVR after updating to current release. 

I got an error in line 55 of blenderVR.py:
  File "/home/jespa/bin/blender-vr/blender-vr/utils/blenderVR.py", line 55, in main
    sys.path.append(os.path.join(BlenderVR_root, 'modules'))
**NameError: name 'BlenderVR_root' is not defined**

I have tried to define it in the previous line, just to receive the same error
in line 54 of console.py:
  File "blender-vr/modules/blendervr/console/console.py", line 54, in __init__
    self._update_loader_script = os.path.join(BlenderVR_root, 'utils',
**NameError: name 'BlenderVR_root' is not defined**

Defining the *BLENDER_VR_ROOT* enviroment variable does not help...

**Comment by jmespadero** [comment]
Ok, I think that the problem is the changes in your last commit 

For example, in line 54 of console.py, you changed the variable name from **blenderVR_root** to **BlenderVR_root**

**Comment by PyrApple** [comment]
For now, I duplicated the current master to new branch: rename-BlenderVR
and reseted the master to commit prior to blenderVR change name.

we do need a dev branch :)

David

**Comment by PyrApple** [comment]
Apologies Dalai, 

I backed up to 
-----------------------------------------------------------------------------
commit ff9d85dd48268b2ef46036c8bd1375989ceec540
Author: David Poirier-Quinot <davipoir@gmail.com>
Date:   Tue Mar 31 19:01:02 2015 +0200

    repaired mistake on win/linux configFiles
-----------------------------------------------------------------------------

while everything was actually fine until the modifs you made @
-----------------------------------------------------------------------------
commit 21bb8bb41474b5b90d225ea0d174f10a2ffd0c8a
Author: Dalai Felinto <dfelinto@gmail.com>
Date:   Tue Apr 7 19:39:38 2015 -0300

    Changes done during IEEE and soon after, mostly by David
    Poirier-Quinot

    * osc api documentation
    * modified osc plugin, weird vehicle/user position issues in sent OSC msgs remain
    * api-related comment modif
    * my first contribution to blenderVR API, thanks Dash!
    * modified .xml config
    * added info in xml files
    * added dk2-like .xml configuration file
    * added requirement-dk2.txt for oculus rift dk2 install (pip3 six and websocket)
    * Run Plugins for all machines (master and clients) -- it needs work
      still
-----------------------------------------------------------------------------
(and can't find a quick way to fix for now)

anyway, everything untouched @ branch rename-BlenderVR.
Will look at it asap.

David

**Comment by PyrApple** [comment]
Fixed (thanks cherry-pick), last master commit is 

---------------------------------------------------------------------------------------------------------
commit a9971a3e6af507828d75db64a5ee16e94047ee45
Author: Dalai Felinto <dfelinto@gmail.com>
Date:   Tue Apr 7 19:39:38 2015 -0300

    Changes done during IEEE and soon after, mostly by David
    Poirier-Quinot

    * osc api documentation
    * modified osc plugin, weird vehicle/user position issues in sent OSC msgs remain
    * api-related comment modif
    * my first contribution to blenderVR API, thanks Dash!
    * modified .xml config
    * added info in xml files
    * added dk2-like .xml configuration file
    * added requirement-dk2.txt for oculus rift dk2 install (pip3 six and websocket)
    * Run Plugins for all machines (master and clients) -- it needs work
      still
---------------------------------------------------------------------------------------------------------

remains BlenderVR rename and jmespadero's commits between 
master and rename-BlenderVR

David

**Comment by jmespadero** [comment]
Well, almost...

I got in the log windows an error like this:
 2015-04-08 14:03:11,803 No environments defined inside configuration file (line 1 of blender-vr/configurations/main-linux.xml)

To solve it, I had to edit the .xml file and change the tag <blenderVR> to <BlenderVR>

**Comment by PyrApple** [comment]
almost..

wen't back to pre-IEEE commits on master for now.

David

**Comment by dfelinto** [comment]
The problem was a mistake in my end, I'm sorry. I didn't realize I had to rename non-Python files as well as the Python ones. Everything should be running smooth in master. (but yes, you need to rename your xml main tag to BlenderVR).

@PyrApple in cases like this you can simply: git revert HEAD (or git revert 7243dc1d5f1f6ad3cb35d2bd94775dee606809f9). git push --force should be avoided by all costs.

And yes we will have a 'dev' branch, but we are waiting for after the 1.0 tag is out. (yet another reason for me to double-check before pushing commits)

**Comment by jmespadero** [comment]
I'm still having problems... the daemons are launching but the keyboard and mouse didn't work anymore. 
I'm not sure if it is my fault after all changes (because I'm quite new user with git). Tomorrow will try again from a new checkout.

Btw, don't feel bad, Dalai.

**Comment by dfelinto** [comment]
That's likely not related to the renaming, but I'll try one of the samples that depend on keyboard. Which setup are you trying? A single computer?

**Comment by jmespadero** [comment]
Yes, It is a single computer with the "Spider" demo and the "console" setting.

**Comment by jmespadero** [comment]
Ok, I have solved it doing a revert to a previous version.
Now, I'm using ce4a5314e3c47c3bcada4538e9fd38d2de649503

**Comment by dfelinto** [comment]
Here it's working fine BUT you need to use the latest sample files as well. There is also a chance you need to re-create the .spider.vr.blend file. So my suggestion is to get the latest samples and make sure you have no .*vr.blend around. Let me know how it goes
